print('Üdv')
nev = str(input('Hogy hívják? ')) 
kor =int(input('Mennyi idős? '))
iskola = str(input('Hol tanul? '))
atlag = float(input('Mennyi az átlaga? '))
print('A válaszait köszönjük szépen!')
